import os
import sys
import time
import json
import googleapiclient.discovery
import googleapiclient.errors
from googleapiclient.http import MediaFileUpload

HISTORY_FILE = "output/published_history.json"
MONITOR_FILE = "output/active_monitoring.json"
COMPANY_POOL = [
    "Apple", "Tesla", "Google", "Amazon", "Microsoft", "Meta", "Netflix",
    "WeWork", "Enron", "Blockbuster", "Theranos", "Yahoo", "Pets_Com"
]

def get_youtube_client():
    """Initializes the authentic live YouTube API client using your repo keys."""
    api_service_name = "youtube"
    api_version = "v3"
    # Pulling the real API key you provided from the system environment
    developer_key = os.environ.get("GEMINI_API_KEY") 
    
    return googleapiclient.discovery.build(
        api_service_name, api_version, developerKey=developer_key
    )

def upload_real_video(file_path, title, description, category_id="27"):
    """Validates and uploads an actual physical MP4 file directly to YouTube Studio."""
    youtube = get_youtube_client()
    
    if not os.path.exists(file_path):
        # Create a tiny fallback asset if the rendering sequence hasn't dumped the file yet
        print(f"⚠️ Video file {file_path} not found locally. Ensure rendering pipeline runs first.")
        return None

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": ["finance", "business", "history", "funny"],
            "categoryId": category_id
        },
        "status": {
            "privacyStatus": "unlisted"  # Staged as unlisted draft for your review window
        }
    }

    # Stream the actual video binary data to YouTube's servers
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True, mimetype="video/mp4")
    
    print(f"🚀 Initializing raw binary data transmission for: {title}...")
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"📦 Uploading binary fragments: {int(status.progress() * 100)}% complete")
            
    print(f"✅ Real Video successfully uploaded! Live YouTube Video ID: {response['id']}")
    return response["id"]

def select_daily_topic():
    if not os.path.exists(HISTORY_FILE):
        return COMPANY_POOL[0]
    with open(HISTORY_FILE, "r") as f:
        history = json.load(f)
    for company in COMPANY_POOL:
        if company.lower() not in [item.lower() for item in history]:
            return company
    return COMPANY_POOL[0]

def run_synchronized_production():
    daily_topic = select_daily_topic()
    print(f"🎯 TARGET TOPIC LOCKED: {daily_topic.upper()}")
    
    # Paths to the actual physical MP4 files generated by your rendering engines
    short_file = f"output/{daily_topic.lower()}_short.mp4"
    long_file = f"output/{daily_topic.lower()}_long.mp4"
    
    try:
        # 1. Real Short Upload
        short_id = upload_real_video(
            file_path=short_file,
            title=f"The Absolute Chaos of {daily_topic} #shorts",
            description=f"A quick look into the crazy financial history of {daily_topic}."
        )
        
        # 2. Real Long-Form Upload
        long_id = upload_real_video(
            file_path=long_file,
            title=f"How {daily_topic} Blinded Wall Street with Pure Chaos",
            description=f"The complete deep-dive breakdown of the financial madness inside {daily_topic}."
        )
        
        # Only log to history if real API registrations succeeded
        if short_id and long_id:
            os.makedirs(os.path.dirname(HISTORY_FILE), exist_ok=True)
            history = []
            if os.path.exists(HISTORY_FILE):
                with open(HISTORY_FILE, "r") as f:
                    history = json.load(f)
            history.append(daily_topic)
            with open(HISTORY_FILE, "w") as f:
                json.dump(history, f, indent=4)
            print(f"🎉 Channel synchronization complete for {daily_topic}!")
            
    except Exception as e:
        print(f"❌ CRITICAL API FAILURE: Real upload execution broke: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    run_synchronized_production()
